# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/lenka/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/lenka/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lenka/Documents/cleanDir/FIT/SUI/proj/proj1/SUI_Project1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lenka/Documents/cleanDir/FIT/SUI/proj/proj1/SUI_Project1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/lenka/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/lenka/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lenka/Documents/cleanDir/FIT/SUI/proj/proj1/SUI_Project1/CMakeFiles /home/lenka/Documents/cleanDir/FIT/SUI/proj/proj1/SUI_Project1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lenka/Documents/cleanDir/FIT/SUI/proj/proj1/SUI_Project1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fc-sui

# Build rule for target.
fc-sui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fc-sui
.PHONY : fc-sui

# fast build rule for target.
fc-sui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/build
.PHONY : fc-sui/fast

#=============================================================================
# Target rules for targets named test-bin

# Build rule for target.
test-bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-bin
.PHONY : test-bin

# fast build rule for target.
test-bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/build
.PHONY : test-bin/fast

card-storage.o: card-storage.cc.o
.PHONY : card-storage.o

# target to build an object file
card-storage.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/card-storage.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/card-storage.cc.o
.PHONY : card-storage.cc.o

card-storage.i: card-storage.cc.i
.PHONY : card-storage.i

# target to preprocess a source file
card-storage.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/card-storage.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/card-storage.cc.i
.PHONY : card-storage.cc.i

card-storage.s: card-storage.cc.s
.PHONY : card-storage.s

# target to generate assembly for a file
card-storage.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/card-storage.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/card-storage.cc.s
.PHONY : card-storage.cc.s

card.o: card.cc.o
.PHONY : card.o

# target to build an object file
card.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/card.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/card.cc.o
.PHONY : card.cc.o

card.i: card.cc.i
.PHONY : card.i

# target to preprocess a source file
card.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/card.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/card.cc.i
.PHONY : card.cc.i

card.s: card.cc.s
.PHONY : card.s

# target to generate assembly for a file
card.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/card.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/card.cc.s
.PHONY : card.cc.s

evaluation-type.o: evaluation-type.cc.o
.PHONY : evaluation-type.o

# target to build an object file
evaluation-type.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/evaluation-type.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/evaluation-type.cc.o
.PHONY : evaluation-type.cc.o

evaluation-type.i: evaluation-type.cc.i
.PHONY : evaluation-type.i

# target to preprocess a source file
evaluation-type.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/evaluation-type.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/evaluation-type.cc.i
.PHONY : evaluation-type.cc.i

evaluation-type.s: evaluation-type.cc.s
.PHONY : evaluation-type.s

# target to generate assembly for a file
evaluation-type.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/evaluation-type.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/evaluation-type.cc.s
.PHONY : evaluation-type.cc.s

fc-sui.o: fc-sui.cc.o
.PHONY : fc-sui.o

# target to build an object file
fc-sui.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/fc-sui.cc.o
.PHONY : fc-sui.cc.o

fc-sui.i: fc-sui.cc.i
.PHONY : fc-sui.i

# target to preprocess a source file
fc-sui.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/fc-sui.cc.i
.PHONY : fc-sui.cc.i

fc-sui.s: fc-sui.cc.s
.PHONY : fc-sui.s

# target to generate assembly for a file
fc-sui.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/fc-sui.cc.s
.PHONY : fc-sui.cc.s

game.o: game.cc.o
.PHONY : game.o

# target to build an object file
game.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/game.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/game.cc.o
.PHONY : game.cc.o

game.i: game.cc.i
.PHONY : game.i

# target to preprocess a source file
game.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/game.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/game.cc.i
.PHONY : game.cc.i

game.s: game.cc.s
.PHONY : game.s

# target to generate assembly for a file
game.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/game.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/game.cc.s
.PHONY : game.cc.s

mem_watch.o: mem_watch.cc.o
.PHONY : mem_watch.o

# target to build an object file
mem_watch.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/mem_watch.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/mem_watch.cc.o
.PHONY : mem_watch.cc.o

mem_watch.i: mem_watch.cc.i
.PHONY : mem_watch.i

# target to preprocess a source file
mem_watch.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/mem_watch.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/mem_watch.cc.i
.PHONY : mem_watch.cc.i

mem_watch.s: mem_watch.cc.s
.PHONY : mem_watch.s

# target to generate assembly for a file
mem_watch.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/mem_watch.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/mem_watch.cc.s
.PHONY : mem_watch.cc.s

memusage.o: memusage.cc.o
.PHONY : memusage.o

# target to build an object file
memusage.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/memusage.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/memusage.cc.o
.PHONY : memusage.cc.o

memusage.i: memusage.cc.i
.PHONY : memusage.i

# target to preprocess a source file
memusage.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/memusage.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/memusage.cc.i
.PHONY : memusage.cc.i

memusage.s: memusage.cc.s
.PHONY : memusage.s

# target to generate assembly for a file
memusage.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/memusage.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/memusage.cc.s
.PHONY : memusage.cc.s

move.o: move.cc.o
.PHONY : move.o

# target to build an object file
move.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/move.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/move.cc.o
.PHONY : move.cc.o

move.i: move.cc.i
.PHONY : move.i

# target to preprocess a source file
move.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/move.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/move.cc.i
.PHONY : move.cc.i

move.s: move.cc.s
.PHONY : move.s

# target to generate assembly for a file
move.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/move.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/move.cc.s
.PHONY : move.cc.s

search-interface.o: search-interface.cc.o
.PHONY : search-interface.o

# target to build an object file
search-interface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/search-interface.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/search-interface.cc.o
.PHONY : search-interface.cc.o

search-interface.i: search-interface.cc.i
.PHONY : search-interface.i

# target to preprocess a source file
search-interface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/search-interface.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/search-interface.cc.i
.PHONY : search-interface.cc.i

search-interface.s: search-interface.cc.s
.PHONY : search-interface.s

# target to generate assembly for a file
search-interface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/search-interface.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/search-interface.cc.s
.PHONY : search-interface.cc.s

strategies-provided.o: strategies-provided.cc.o
.PHONY : strategies-provided.o

# target to build an object file
strategies-provided.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/strategies-provided.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/strategies-provided.cc.o
.PHONY : strategies-provided.cc.o

strategies-provided.i: strategies-provided.cc.i
.PHONY : strategies-provided.i

# target to preprocess a source file
strategies-provided.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/strategies-provided.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/strategies-provided.cc.i
.PHONY : strategies-provided.cc.i

strategies-provided.s: strategies-provided.cc.s
.PHONY : strategies-provided.s

# target to generate assembly for a file
strategies-provided.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/strategies-provided.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/strategies-provided.cc.s
.PHONY : strategies-provided.cc.s

sui-solution.o: sui-solution.cc.o
.PHONY : sui-solution.o

# target to build an object file
sui-solution.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/sui-solution.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/sui-solution.cc.o
.PHONY : sui-solution.cc.o

sui-solution.i: sui-solution.cc.i
.PHONY : sui-solution.i

# target to preprocess a source file
sui-solution.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/sui-solution.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/sui-solution.cc.i
.PHONY : sui-solution.cc.i

sui-solution.s: sui-solution.cc.s
.PHONY : sui-solution.s

# target to generate assembly for a file
sui-solution.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fc-sui.dir/build.make CMakeFiles/fc-sui.dir/sui-solution.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/sui-solution.cc.s
.PHONY : sui-solution.cc.s

test-main.o: test-main.cc.o
.PHONY : test-main.o

# target to build an object file
test-main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/test-main.cc.o
.PHONY : test-main.cc.o

test-main.i: test-main.cc.i
.PHONY : test-main.i

# target to preprocess a source file
test-main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/test-main.cc.i
.PHONY : test-main.cc.i

test-main.s: test-main.cc.s
.PHONY : test-main.s

# target to generate assembly for a file
test-main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/test-main.cc.s
.PHONY : test-main.cc.s

test.o: test.cc.o
.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i
.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s
.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-bin.dir/build.make CMakeFiles/test-bin.dir/test.cc.s
.PHONY : test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fc-sui"
	@echo "... test-bin"
	@echo "... card-storage.o"
	@echo "... card-storage.i"
	@echo "... card-storage.s"
	@echo "... card.o"
	@echo "... card.i"
	@echo "... card.s"
	@echo "... evaluation-type.o"
	@echo "... evaluation-type.i"
	@echo "... evaluation-type.s"
	@echo "... fc-sui.o"
	@echo "... fc-sui.i"
	@echo "... fc-sui.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... mem_watch.o"
	@echo "... mem_watch.i"
	@echo "... mem_watch.s"
	@echo "... memusage.o"
	@echo "... memusage.i"
	@echo "... memusage.s"
	@echo "... move.o"
	@echo "... move.i"
	@echo "... move.s"
	@echo "... search-interface.o"
	@echo "... search-interface.i"
	@echo "... search-interface.s"
	@echo "... strategies-provided.o"
	@echo "... strategies-provided.i"
	@echo "... strategies-provided.s"
	@echo "... sui-solution.o"
	@echo "... sui-solution.i"
	@echo "... sui-solution.s"
	@echo "... test-main.o"
	@echo "... test-main.i"
	@echo "... test-main.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

